# Generated by Django 4.2.6 on 2023-10-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_canchas_tenistas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Canchas',
            new_name='Cancha',
        ),
        migrations.RenameModel(
            old_name='Tenistas',
            new_name='Tenista',
        ),
    ]
